# Generated by Django 5.2.4 on 2025-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20),
        ),
    ]
