# Generated by Django 5.2.4 on 2025-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_answer_code_alter_task_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='explanation_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='explanation_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='title_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20),
        ),
    ]
